spring.application.name=RabbitMQ

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.rabbitmq.listener.simple.prefetch=10
#prefetch Give only 1 unacknowledged message to each consumer at a time.
spring.rabbitmq.listener.simple.acknowledge-mode=manual   
#basicAck() / basicNack()

spring.rabbitmq.listener.simple.concurrency=2
spring.rabbitmq.listener.simple.max-concurrency=5

#Start with 2 consumers.
#Spring can increase up to 5 consumers if load increases.



#spring.rabbitmq.listener.simple.retry.enabled=true
#
#spring.rabbitmq.listener.simple.retry.initial-interval=1000
#
#spring.rabbitmq.listener.simple.retry.max-attempts=3
#
#spring.rabbitmq.listener.simple.retry.multiplier=2


spring.rabbitmq.publisher-confirm-type=correlated

spring.rabbitmq.publisher-returns=true

#Helps the producer know whether RabbitMQ successfully accepted the message.



spring.rabbitmq.connection-timeout=10000

spring.rabbitmq.requested-heartbeat=30